version: "3.1"
services:
  database:
    image: mariadb:10.5
    ports:
      - "3330:3306"
    volumes:
      - ./data:/var/lib/mysql
    environment:
      - "MARIADB_ROOT_USER=${USR}"
      - "MARIADB_ROOT_PASSWORD=${PASS}"
  