spring:
 flyway:
  create-schemas: true
  schemas: messanger
  url: jdbc:mariadb://localhost:3330/
  user: ${USER}
  password: ${PASSWORD}
 datasource:
  url: jdbc:mariadb://localhost:3330/messanger
  username: ${USER}
  password: ${PASSWORD}

admin: sandro